"""add_game_challenge_and_user_balance

Revision ID: 08724a3d75f5
Revises: 20251205_160525
Create Date: 2025-12-05 21:57:06.291996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08724a3d75f5'
down_revision: Union[str, None] = '20251205_160525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.Column('start_price', sa.Integer(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('current_highest_bid_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_highest_bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('bidder_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['bidder_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_forum', sa.Boolean(), nullable=False),
    sa.Column('summary_topic_id', sa.Integer(), nullable=True),
    sa.Column('creative_topic_id', sa.Integer(), nullable=True),
    sa.Column('active_topic_id', sa.Integer(), nullable=True),
    sa.Column('auto_reply_chance', sa.Float(), nullable=False),
    sa.Column('moderation_mode', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('game_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('challenger_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('game_type', sa.String(length=32), nullable=False),
    sa.Column('bet_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_challenges_challenger_id'), 'game_challenges', ['challenger_id'], unique=False)
    op.create_index(op.f('ix_game_challenges_chat_id'), 'game_challenges', ['chat_id'], unique=False)
    op.create_index(op.f('ix_game_challenges_status'), 'game_challenges', ['status'], unique=False)
    op.create_index(op.f('ix_game_challenges_target_id'), 'game_challenges', ['target_id'], unique=False)
    op.create_table('global_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('period_type', sa.String(length=64), nullable=False),
    sa.Column('total_pvp_wins', sa.Integer(), nullable=False),
    sa.Column('pvp_wins_delta', sa.Integer(), nullable=False),
    sa.Column('total_grow_count', sa.Integer(), nullable=False),
    sa.Column('grow_count_delta', sa.Integer(), nullable=False),
    sa.Column('total_casino_jackpots', sa.Integer(), nullable=False),
    sa.Column('casino_jackpots_delta', sa.Integer(), nullable=False),
    sa.Column('total_reputation', sa.Integer(), nullable=False),
    sa.Column('reputation_delta', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_stats_date'), 'global_stats', ['date'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('has_link', sa.Boolean(), nullable=False),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('moderation_configs',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('enabled_features', sa.Text(), nullable=True),
    sa.Column('banned_words', sa.Text(), nullable=True),
    sa.Column('flood_threshold', sa.Integer(), nullable=False),
    sa.Column('spam_link_protection', sa.Boolean(), nullable=False),
    sa.Column('swear_filter', sa.Boolean(), nullable=False),
    sa.Column('auto_warn_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('pending_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('welcome_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_kicked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_verifications_chat_id'), 'pending_verifications', ['chat_id'], unique=False)
    op.create_index(op.f('ix_pending_verifications_user_id'), 'pending_verifications', ['user_id'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reward_type', sa.String(length=64), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_code'), 'quests', ['code'], unique=True)
    op.create_table('spam_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern')
    )
    op.create_table('toxicity_configs',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('mute_duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('user_balances',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('total_won', sa.Integer(), nullable=False),
    sa.Column('total_lost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_chat_id'), 'admins', ['chat_id'], unique=False)
    op.create_index(op.f('ix_admins_user_id'), 'admins', ['user_id'], unique=False)
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_user_id'), 'blacklist', ['user_id'], unique=False)
    op.create_table('duo_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('user1_id < user2_id', name='_user1_lt_user2_cc'),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='_user1_user2_uc')
    )
    op.create_table('game_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('size_cm', sa.Integer(), nullable=False),
    sa.Column('next_grow_at', sa.DateTime(), nullable=True),
    sa.Column('pvp_wins', sa.Integer(), nullable=False),
    sa.Column('grow_count', sa.Integer(), nullable=False),
    sa.Column('casino_jackpots', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_game_stats_tg_user_id'), 'game_stats', ['tg_user_id'], unique=True)
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guilds_name'), 'guilds', ['name'], unique=True)
    op.create_table('private_chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_history', sa.Text(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=False),
    sa.Column('toxicity_level', sa.Float(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_chats_user_id'), 'private_chats', ['user_id'], unique=True)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('is_golden_fund', sa.Boolean(), nullable=False),
    sa.Column('is_sticker', sa.Boolean(), nullable=False),
    sa.Column('sticker_file_id', sa.String(length=255), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_created_at'), 'quotes', ['created_at'], unique=False)
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=False)
    op.create_table('toxicity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('action_taken', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toxicity_logs_chat_id'), 'toxicity_logs', ['chat_id'], unique=False)
    op.create_table('trade_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.create_table('user_question_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('asked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_quests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'quest_id')
    )
    op.create_table('wallets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('warnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warnings_user_id'), 'warnings', ['user_id'], unique=False)
    op.create_table('duo_stats',
    sa.Column('duo_team_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['duo_team_id'], ['duo_teams.id'], ),
    sa.PrimaryKeyConstraint('duo_team_id')
    )
    op.create_table('guild_members',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('team_wars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('declarer_guild_id', sa.Integer(), nullable=False),
    sa.Column('defender_guild_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('winner_guild_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['declarer_guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['defender_guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['winner_guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_war_participants',
    sa.Column('team_war_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['team_war_id'], ['team_wars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('team_war_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_war_participants')
    op.drop_table('team_wars')
    op.drop_table('guild_members')
    op.drop_table('duo_stats')
    op.drop_index(op.f('ix_warnings_user_id'), table_name='warnings')
    op.drop_table('warnings')
    op.drop_table('wallets')
    op.drop_table('user_quests')
    op.drop_table('user_question_history')
    op.drop_table('user_achievements')
    op.drop_table('trade_offers')
    op.drop_index(op.f('ix_toxicity_logs_chat_id'), table_name='toxicity_logs')
    op.drop_table('toxicity_logs')
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_created_at'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_private_chats_user_id'), table_name='private_chats')
    op.drop_table('private_chats')
    op.drop_index(op.f('ix_guilds_name'), table_name='guilds')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_game_stats_tg_user_id'), table_name='game_stats')
    op.drop_table('game_stats')
    op.drop_table('duo_teams')
    op.drop_index(op.f('ix_blacklist_user_id'), table_name='blacklist')
    op.drop_table('blacklist')
    op.drop_index(op.f('ix_admins_user_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_chat_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_balances')
    op.drop_table('toxicity_configs')
    op.drop_table('spam_patterns')
    op.drop_index(op.f('ix_quests_code'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_pending_verifications_user_id'), table_name='pending_verifications')
    op.drop_index(op.f('ix_pending_verifications_chat_id'), table_name='pending_verifications')
    op.drop_table('pending_verifications')
    op.drop_table('moderation_configs')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_global_stats_date'), table_name='global_stats')
    op.drop_table('global_stats')
    op.drop_index(op.f('ix_game_challenges_target_id'), table_name='game_challenges')
    op.drop_index(op.f('ix_game_challenges_status'), table_name='game_challenges')
    op.drop_index(op.f('ix_game_challenges_chat_id'), table_name='game_challenges')
    op.drop_index(op.f('ix_game_challenges_challenger_id'), table_name='game_challenges')
    op.drop_table('game_challenges')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_table('bids')
    op.drop_table('auctions')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
