"""Add trading system v9.5 - trades, market, auctions

Revision ID: 71b4acfaa9ed
Revises: 042d107b23a8
Create Date: 2026-01-28 12:32:07.492131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b4acfaa9ed'
down_revision: Union[str, None] = '042d107b23a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('item_data', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_user_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_listings_chat_id'), 'market_listings', ['chat_id'], unique=False)
    op.create_index(op.f('ix_market_listings_created_at'), 'market_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_listings_seller_user_id'), 'market_listings', ['seller_user_id'], unique=False)
    op.create_index(op.f('ix_market_listings_status'), 'market_listings', ['status'], unique=False)
    op.create_table('quote_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_blacklist',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_security_blacklist_expires_at'), 'security_blacklist', ['expires_at'], unique=False)
    op.create_table('sticker_packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('offer_items', sa.Text(), nullable=True),
    sa.Column('offer_coins', sa.Integer(), nullable=False),
    sa.Column('request_items', sa.Text(), nullable=True),
    sa.Column('request_coins', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_chat_id'), 'trades', ['chat_id'], unique=False)
    op.create_index(op.f('ix_trades_from_user_id'), 'trades', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_to_user_id'), 'trades', ['to_user_id'], unique=False)
    op.create_table('auction_bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('bidder_user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_bids_auction_id'), 'auction_bids', ['auction_id'], unique=False)
    op.create_index(op.f('ix_auction_bids_bidder_user_id'), 'auction_bids', ['bidder_user_id'], unique=False)
    op.drop_table('bids')
    op.drop_table('trade_offers')
    # Skip dropping foreign key constraints for SQLite compatibility
    # op.drop_constraint(None, 'admins', type_='foreignkey')
    
    # Use batch mode for SQLite to modify auctions table
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.BigInteger(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('item_data', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('current_price', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('winner_user_id', sa.BigInteger(), nullable=True))
        batch_op.alter_column('seller_user_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False)
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=64),
                   type_=sa.String(length=16),
                   existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_auctions_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auctions_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auctions_seller_user_id'), ['seller_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auctions_status'), ['status'], unique=False)
        batch_op.drop_column('current_highest_bid_id')
        batch_op.drop_column('item_type')
        batch_op.drop_column('item_quantity')
    
    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona', sa.String(length=20), nullable=False, server_default='oleg'))
        batch_op.alter_column('pvp_accept_timeout',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_server_default=sa.text('(60)'))
    
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.alter_column('pvp_losses',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_server_default=sa.text('0'))
    
    with op.batch_alter_table('marriage_proposals', schema=None) as batch_op:
        batch_op.alter_column('created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=16),
                   nullable=False,
                   existing_server_default=sa.text("'pending'"))
        batch_op.create_unique_constraint('uq_proposal_pending', ['from_user_id', 'to_user_id', 'chat_id', 'status'])
    
    with op.batch_alter_table('marriages', schema=None) as batch_op:
        batch_op.alter_column('married_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        batch_op.create_unique_constraint('uq_marriage_users_chat', ['user1_id', 'user2_id', 'chat_id'])
    
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'topic_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint('uq_marriage_users_chat', 'marriages', type_='unique')
    op.alter_column('marriages', 'married_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_constraint('uq_proposal_pending', 'marriage_proposals', type_='unique')
    op.alter_column('marriage_proposals', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('marriage_proposals', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('game_stats', 'pvp_losses',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bot_configs', 'pvp_accept_timeout',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(60)'))
    op.drop_column('bot_configs', 'persona')
    op.add_column('auctions', sa.Column('item_quantity', sa.INTEGER(), nullable=False))
    op.add_column('auctions', sa.Column('item_type', sa.VARCHAR(length=64), nullable=False))
    op.add_column('auctions', sa.Column('current_highest_bid_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'auctions', 'bids', ['current_highest_bid_id'], ['id'])
    op.create_foreign_key(None, 'auctions', 'users', ['seller_user_id'], ['id'])
    op.drop_index(op.f('ix_auctions_status'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_seller_user_id'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_ends_at'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_chat_id'), table_name='auctions')
    op.alter_column('auctions', 'status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('auctions', 'seller_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('auctions', 'winner_user_id')
    op.drop_column('auctions', 'completed_at')
    op.drop_column('auctions', 'current_price')
    op.drop_column('auctions', 'item_data')
    op.drop_column('auctions', 'chat_id')
    op.create_foreign_key(None, 'admins', 'users', ['user_id'], ['tg_user_id'])
    op.create_table('trade_offers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_user_id', sa.INTEGER(), nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('item_quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('auction_id', sa.INTEGER(), nullable=False),
    sa.Column('bidder_user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['bidder_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_auction_bids_bidder_user_id'), table_name='auction_bids')
    op.drop_index(op.f('ix_auction_bids_auction_id'), table_name='auction_bids')
    op.drop_table('auction_bids')
    op.drop_index(op.f('ix_trades_to_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_from_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_chat_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('sticker_packs')
    op.drop_index(op.f('ix_security_blacklist_expires_at'), table_name='security_blacklist')
    op.drop_table('security_blacklist')
    op.drop_table('quotes')
    op.drop_table('quote_votes')
    op.drop_index(op.f('ix_market_listings_status'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_seller_user_id'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_created_at'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_chat_id'), table_name='market_listings')
    op.drop_table('market_listings')
    # ### end Alembic commands ###
